defaults: &defaults
  twitter:
    api_key: "k0gjhoyYg3nPc0ii5hPCUOoq0"
    api_secret: "KqlVdYdp7iGCrDeM60S3ho3mHi50D3FtsoqfulXjJZGWxUuolR"
  facebook:
    api_key: "251631695196822"
    api_secret: "4b2b1f2decd0d192c5f207e0b4d99a98"
  instagram:
    api_key: "a483fb2107d54d0ba9f9ffa7d09ae1f4"
    api_secret: db507384f27f48afa8f46b3958d57482

development:
  <<: *defaults

test:
  <<: *defaults

production:
  twitter:
    api_key: "4aqRX08s94UeMVrp5zIBsPfIb"
    api_secret: "RmXZQQY7cOYLUThalZV8Lfixs0PiVbABoR1DJUjzne8XCq5xFo"
  facebook:
    api_key: "251607648532560"
    api_secret: "ab77e359d0d26a16ba3b1aef942ffa65"
  instagram:
    api_key: "a0a613a5aff243c6838ab4486e57be92"
    api_secret: "e59c3af03995425589ba4bfabe492851"
